name: Build HTML from Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Convert Markdown to HTML Main page
        uses: jaywcjlove/markdown-to-html-cli@v5.0.3
        with:
          source: Main page.md
          output: Main-page.html

      - name: Convert Markdown to HTML (Locations)
        run: |
          find Locations -name "*.md" | while read file; do
            html="${file%.md}.html"
            npx markdown-to-html-cli --source "$file" --output "$html"
          done

      - name: Deploy to main
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: publish_main
